import { Source_Sans_3, Playfair_Display } from "next/font/google";
import "./globals.css";

import { ToastProvider } from "@/components/Toast";

const Primary = Playfair_Display({
  variable: "--font-Playfair_Display-Serif",
  subsets: ["latin"],
  display: "swap",
});
const Secondary = Source_Sans_3({
  variable: "--font-Source_Sans_3-sans-serif",
  subsets: ["latin"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${Primary.variable}${Secondary.variable} antialiased`}
      >
            <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
